# automatically generated by the FlatBuffers compiler, do not modify

# namespace: xcom

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ViewItem(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ViewItem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsViewItem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ViewItem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ViewItem
    def Views(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ViewItem
    def Heat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ViewItem
    def Dt1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return None

    # ViewItem
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ViewItem
    def City(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ViewItem
    def Tag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ViewItem
    def Txt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ViewItemStart(builder):
    builder.StartObject(7)

def ViewItemAddViews(builder, views):
    builder.PrependInt32Slot(0, views, 0)

def ViewItemAddHeat(builder, heat):
    builder.PrependFloat32Slot(1, heat, 0.0)

def ViewItemAddDt1(builder, dt1):
    builder.PrependInt64Slot(2, dt1, None)

def ViewItemAddId(builder, id):
    builder.PrependInt64Slot(3, id, 0)

def ViewItemAddCity(builder, city):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(city), 0)

def ViewItemAddTag(builder, tag):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(tag), 0)

def ViewItemAddTxt(builder, txt):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(txt), 0)

def ViewItemEnd(builder):
    return builder.EndObject()


try:
    from typing import Optional
except:
    pass

class ViewItemT(object):

    # ViewItemT
    def __init__(
        self,
        views = 0,
        heat = 0.0,
        dt1 = None,
        id = 0,
        city = None,
        tag = None,
        txt = None,
    ):
        self.views = views  # type: int
        self.heat = heat  # type: float
        self.dt1 = dt1  # type: Optional[int]
        self.id = id  # type: int
        self.city = city  # type: Optional[str]
        self.tag = tag  # type: Optional[str]
        self.txt = txt  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        viewItem = ViewItem()
        viewItem.Init(buf, pos)
        return cls.InitFromObj(viewItem)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, viewItem):
        x = ViewItemT()
        x._UnPack(viewItem)
        return x

    # ViewItemT
    def _UnPack(self, viewItem):
        if viewItem is None:
            return
        self.views = viewItem.Views()
        self.heat = viewItem.Heat()
        self.dt1 = viewItem.Dt1()
        self.id = viewItem.Id()
        self.city = viewItem.City()
        self.tag = viewItem.Tag()
        self.txt = viewItem.Txt()

    # ViewItemT
    def Pack(self, builder):
        if self.city is not None:
            city = builder.CreateString(self.city)
        if self.tag is not None:
            tag = builder.CreateString(self.tag)
        if self.txt is not None:
            txt = builder.CreateString(self.txt)
        ViewItemStart(builder)
        ViewItemAddViews(builder, self.views)
        ViewItemAddHeat(builder, self.heat)
        ViewItemAddDt1(builder, self.dt1)
        ViewItemAddId(builder, self.id)
        if self.city is not None:
            ViewItemAddCity(builder, city)
        if self.tag is not None:
            ViewItemAddTag(builder, tag)
        if self.txt is not None:
            ViewItemAddTxt(builder, txt)
        viewItem = ViewItemEnd(builder)
        return viewItem


class ViewList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ViewList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsViewList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ViewList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ViewList
    def Dts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ViewList
    def DtsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # ViewList
    def DtsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ViewList
    def DtsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ViewList
    def List(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ViewItem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ViewList
    def ListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ViewList
    def ListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ViewListStart(builder):
    builder.StartObject(2)

def ViewListAddDts(builder, dts):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dts), 0)

def ViewListStartDtsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def ViewListCreateDtsVector(builder, data):
    data = list(data)
    builder.StartVector(8, len(data), 8)
    for item in reversed(data):
        builder.PrependInt64(item)
    return builder.EndVector()

def ViewListAddList(builder, list):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(list), 0)

def ViewListStartListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ViewListCreateListVector(builder, data):
    return builder.CreateVectorOfTables(data)

def ViewListEnd(builder):
    return builder.EndObject()


try:
    from typing import List
except:
    pass

class ViewListT(object):

    # ViewListT
    def __init__(
        self,
        dts = None,
        list = None,
    ):
        self.dts = dts  # type: Optional[List[int]]
        self.list = list  # type: Optional[List[ViewItemT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        viewList = ViewList()
        viewList.Init(buf, pos)
        return cls.InitFromObj(viewList)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, viewList):
        x = ViewListT()
        x._UnPack(viewList)
        return x

    # ViewListT
    def _UnPack(self, viewList):
        if viewList is None:
            return
        if not viewList.DtsIsNone():
            if np is None:
                self.dts = []
                for i in range(viewList.DtsLength()):
                    self.dts.append(viewList.Dts(i))
            else:
                self.dts = viewList.DtsAsNumpy()
        if not viewList.ListIsNone():
            self.list = []
            for i in range(viewList.ListLength()):
                if viewList.List(i) is None:
                    self.list.append(None)
                else:
                    viewItem_ = ViewItemT.InitFromObj(viewList.List(i))
                    self.list.append(viewItem_)

    # ViewListT
    def Pack(self, builder):
        if self.dts is not None:
            if np is not None and type(self.dts) is np.ndarray:
                dts = builder.CreateNumpyVector(self.dts)
            else:
                ViewListStartDtsVector(builder, len(self.dts))
                for i in reversed(range(len(self.dts))):
                    builder.PrependInt64(self.dts[i])
                dts = builder.EndVector()
        if self.list is not None:
            listlist = []
            for i in range(len(self.list)):
                listlist.append(self.list[i].Pack(builder))
            ViewListStartListVector(builder, len(self.list))
            for i in reversed(range(len(self.list))):
                builder.PrependUOffsetTRelative(listlist[i])
            list = builder.EndVector()
        ViewListStart(builder)
        if self.dts is not None:
            ViewListAddDts(builder, dts)
        if self.list is not None:
            ViewListAddList(builder, list)
        viewList = ViewListEnd(builder)
        return viewList


