// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
import { ViewItem } from '../xcom/view-item.js';
export class ViewList {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsViewList(bb, obj) {
        return (obj || new ViewList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsViewList(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ViewList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    dts(index) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt64(this.bb.__vector(this.bb_pos + offset) + index * 8) : BigInt(0);
    }
    dtsLength() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    list(index, obj) {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? (obj || new ViewItem()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    }
    listLength() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    static startViewList(builder) {
        builder.startObject(2);
    }
    static addDts(builder, dtsOffset) {
        builder.addFieldOffset(0, dtsOffset, 0);
    }
    static createDtsVector(builder, data) {
        builder.startVector(8, data.length, 8);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addInt64(data[i]);
        }
        return builder.endVector();
    }
    static startDtsVector(builder, numElems) {
        builder.startVector(8, numElems, 8);
    }
    static addList(builder, listOffset) {
        builder.addFieldOffset(1, listOffset, 0);
    }
    static createListVector(builder, data) {
        builder.startVector(4, data.length, 4);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }
    static startListVector(builder, numElems) {
        builder.startVector(4, numElems, 4);
    }
    static endViewList(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static finishViewListBuffer(builder, offset) {
        builder.finish(offset);
    }
    static finishSizePrefixedViewListBuffer(builder, offset) {
        builder.finish(offset, undefined, true);
    }
    static createViewList(builder, dtsOffset, listOffset) {
        ViewList.startViewList(builder);
        ViewList.addDts(builder, dtsOffset);
        ViewList.addList(builder, listOffset);
        return ViewList.endViewList(builder);
    }
}
