// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ViewItem } from '../xcom/view-item.js';


export class ViewList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ViewList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsViewList(bb:flatbuffers.ByteBuffer, obj?:ViewList):ViewList {
  return (obj || new ViewList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsViewList(bb:flatbuffers.ByteBuffer, obj?:ViewList):ViewList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ViewList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

dts(index: number):bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : BigInt(0);
}

dtsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

list(index: number, obj?:ViewItem):ViewItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ViewItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

listLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startViewList(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addDts(builder:flatbuffers.Builder, dtsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, dtsOffset, 0);
}

static createDtsVector(builder:flatbuffers.Builder, data:bigint[]):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]!);
  }
  return builder.endVector();
}

static startDtsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
}

static addList(builder:flatbuffers.Builder, listOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, listOffset, 0);
}

static createListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endViewList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishViewListBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedViewListBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createViewList(builder:flatbuffers.Builder, dtsOffset:flatbuffers.Offset, listOffset:flatbuffers.Offset):flatbuffers.Offset {
  ViewList.startViewList(builder);
  ViewList.addDts(builder, dtsOffset);
  ViewList.addList(builder, listOffset);
  return ViewList.endViewList(builder);
}
}
