// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
export class ViewItem {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsViewItem(bb, obj) {
        return (obj || new ViewItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsViewItem(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ViewItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    views() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    }
    heat() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    dt1() {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readInt64(this.bb_pos + offset) : null;
    }
    id() {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.readInt64(this.bb_pos + offset) : BigInt('0');
    }
    city(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    tag(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    txt(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 16);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    static startViewItem(builder) {
        builder.startObject(7);
    }
    static addViews(builder, views) {
        builder.addFieldInt32(0, views, 0);
    }
    static addHeat(builder, heat) {
        builder.addFieldFloat32(1, heat, 0.0);
    }
    static addDt1(builder, dt1) {
        builder.addFieldInt64(2, dt1, null);
    }
    static addId(builder, id) {
        builder.addFieldInt64(3, id, BigInt('0'));
    }
    static addCity(builder, cityOffset) {
        builder.addFieldOffset(4, cityOffset, 0);
    }
    static addTag(builder, tagOffset) {
        builder.addFieldOffset(5, tagOffset, 0);
    }
    static addTxt(builder, txtOffset) {
        builder.addFieldOffset(6, txtOffset, 0);
    }
    static endViewItem(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createViewItem(builder, views, heat, dt1, id, cityOffset, tagOffset, txtOffset) {
        ViewItem.startViewItem(builder);
        ViewItem.addViews(builder, views);
        ViewItem.addHeat(builder, heat);
        if (dt1 !== null)
            ViewItem.addDt1(builder, dt1);
        ViewItem.addId(builder, id);
        ViewItem.addCity(builder, cityOffset);
        ViewItem.addTag(builder, tagOffset);
        ViewItem.addTxt(builder, txtOffset);
        return ViewItem.endViewItem(builder);
    }
}
